// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcSJydH3dm6YEkYrsyqwd3VMGfbvJCG4',
    appId: '1:952217304228:web:58d260ec461850a362fa31',
    messagingSenderId: '952217304228',
    projectId: 'flutter-project-am',
    authDomain: 'flutter-project-am.firebaseapp.com',
    storageBucket: 'flutter-project-am.appspot.com',
    measurementId: 'G-3W643EGJXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFKtoHdGIqqTLi5ef8MTbln-MAvMN3YiE',
    appId: '1:952217304228:android:44c77fcd0cf6618362fa31',
    messagingSenderId: '952217304228',
    projectId: 'flutter-project-am',
    storageBucket: 'flutter-project-am.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4yn0dCNz__OyRrfD69KtXpRps7p1jXKQ',
    appId: '1:952217304228:ios:9b8413a4a77fba7c62fa31',
    messagingSenderId: '952217304228',
    projectId: 'flutter-project-am',
    storageBucket: 'flutter-project-am.appspot.com',
    iosBundleId: 'online.gshdev.mynotes',
  );
}
